// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwYEEy02lJ_q57yh9v4KI0TFP1_0AgnRs',
    appId: '1:58878061940:android:06f10995fa54ef98301021',
    messagingSenderId: '58878061940',
    projectId: 'consultation-service-3ad34',
    storageBucket: 'consultation-service-3ad34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDo_59XtvdVp0kdt-Q9AF9wvIvUNMMBKc',
    appId: '1:58878061940:ios:e319cef75b2cef80301021',
    messagingSenderId: '58878061940',
    projectId: 'consultation-service-3ad34',
    storageBucket: 'consultation-service-3ad34.firebasestorage.app',
    iosBundleId: 'com.consultation.consultationServiceApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvXS_QIwyI1MJUo-_1WQq-Abf3nhyt5Co',
    appId: '1:58878061940:web:f7238e761941f304301021',
    messagingSenderId: '58878061940',
    projectId: 'consultation-service-3ad34',
    authDomain: 'consultation-service-3ad34.firebaseapp.com',
    storageBucket: 'consultation-service-3ad34.firebasestorage.app',
    measurementId: 'G-2EK38X2H8K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDo_59XtvdVp0kdt-Q9AF9wvIvUNMMBKc',
    appId: '1:58878061940:ios:e319cef75b2cef80301021',
    messagingSenderId: '58878061940',
    projectId: 'consultation-service-3ad34',
    storageBucket: 'consultation-service-3ad34.firebasestorage.app',
    iosBundleId: 'com.consultation.consultationServiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvXS_QIwyI1MJUo-_1WQq-Abf3nhyt5Co',
    appId: '1:58878061940:web:2b305258bf921c6d301021',
    messagingSenderId: '58878061940',
    projectId: 'consultation-service-3ad34',
    authDomain: 'consultation-service-3ad34.firebaseapp.com',
    storageBucket: 'consultation-service-3ad34.firebasestorage.app',
    measurementId: 'G-QGEGLT2QXK',
  );

}